<<<<<<< HEAD
version: '3'

services:
  email:
    image: maildev/maildev
    ports:
      - "25:25"
=======
version: '3'

services:
  email:
    image: maildev/maildev
    ports:
      - "25:25"
>>>>>>> a426eca87f2e51c833015759247d81550335fcda
      - 8000:80